### PR TITLE
FIX embarassing typo

### PR DESCRIPTION
**Pull request by fabianp**
Dear mlresearch editors,

if possible I would like to correct an embarrassing typo in the central result of my paper. Right now the central result of the paper (Theorem 2) has a condition that the errors (\varepsilon) need to be summable:

image

The inequality in the equation doesn't mean anything since it allows it to be infinity and should be a strict inequality instead of \leq. Hence, I would like to replace it with the correct version:

image

This PR contains both the .pdf with this fix and the associated supplementary material (which is just a PDF with paper + appendix).

Thanks in advance for your time.

### CODE REVIEW

**Comment by lawrennd** [comment]
No probs, thanks for the update Fabian!

**Comment by fabianp** [comment]
Thanks @lawrennd, this means a lot to me!

**Comment by lawrennd** [comment]
It's the beauty of a github hosted proceedings!

**Comment by fabianp** [comment]
this is indeed the future! I'm also blown away by the fact that update appeared immediate on the proceedings webpage

**Pull request merged**
